events {}

http {

    upstream amazon_backend {
        server amazon-app:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://amazon_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
